"""File that contains constant values like PMD rules and their assignment to rulesets or the date they were introduced."""

# default rules for the maven pmd plugin: https://maven.apache.org/plugins/maven-pmd-plugin/examples/usingRuleSets.html
MVN_DEFAULT = [
'AvoidUsingHardCodedIP',
'CheckResultSet',
'UnusedFormalParameter',
'UnusedLocalVariable',
'UnusedPrivateField',
'UnusedPrivateMethod',
'DontImportJavaLang',
'DuplicateImports',
'ExtendsObject',
'ForLoopShouldBeWhileLoop',
'TooManyStaticImports',
'UnnecessaryFullyQualifiedName',
'UnnecessaryModifier',
'UnnecessaryReturn',
'UselessParentheses',
'UselessQualifiedThis',
'CollapsibleIfStatements',
'SimplifiedTernary',
'UselessOverridingMethod',
'AvoidBranchingStatementAsLastInLoop',
'AvoidDecimalLiteralsInBigDecimalConstructor',
'AvoidMultipleUnaryOperators',
'AvoidUsingOctalValues',
'BrokenNullCheck',
'CheckSkipResult',
'ClassCastExceptionWithToArray',
'DontUseFloatTypeForLoopIndices',
'EmptyCatchBlock',
'EmptyFinallyBlock',
'EmptyIfStmt',
'EmptyInitializer',
'EmptyStatementBlock',
'EmptyStatementNotInLoop',
'EmptySwitchStatements',
'EmptySynchronizedBlock',
'EmptyTryBlock',
'EmptyWhileStmt',
'ImportFromSamePackage',
'JumbledIncrementer',
'MisplacedNullCheck',
'OverrideBothEqualsAndHashcode',
'ReturnFromFinallyBlock',
'UnconditionalIfStatement',
'UnnecessaryConversionTemporary',
'UnusedNullCheckInEquals',
'UselessOperationOnImmutable',
'AvoidThreadGroup',
'DontCallThreadRun',
'DoubleCheckedLocking',
'BigIntegerInstantiation',
'BooleanInstantiation',
]


PMD_RULES_SINCE = {
 'PMD_AAA': {'pmd_category': 'controversial',
             'pmd_name': 'AvoidAccessibilityAlteration',
             'pmd_since': '4.1'},
 'PMD_AAL': {'pmd_category': 'optimizations',
             'pmd_name': 'AvoidArrayLoops',
             'pmd_since': '3.5'},
 'PMD_ABSALIL': {'pmd_category': 'basic',
                 'pmd_name': 'AvoidBranchingStatementAsLastInLoop',
                 'pmd_since': '5.0'},
 'PMD_ACF': {'pmd_category': 'finalizers',
             'pmd_name': 'AvoidCallingFinalize',
             'pmd_since': '3.0'},
 'PMD_ACGE': {'pmd_category': 'strictexception',
              'pmd_name': 'AvoidCatchingGenericException',
              'pmd_since': '4.2.6'},
 'PMD_ACI': {'pmd_category': 'design',
             'pmd_name': 'AvoidConstantsInterface',
             'pmd_since': '3.5'},
 'PMD_ACNPE': {'pmd_category': 'strictexception',
               'pmd_name': 'AvoidCatchingNPE',
               'pmd_since': '1.8'},
 'PMD_ACT': {'pmd_category': 'strictexception',
             'pmd_name': 'AvoidCatchingThrowable',
             'pmd_since': '1.2'},
 'PMD_ACWAM': {'pmd_category': 'design',
               'pmd_name': 'AbstractClassWithoutAbstractMethod',
               'pmd_since': '3.0'},
 'PMD_ADL': {'pmd_category': 'strings',
             'pmd_name': 'AvoidDuplicateLiterals',
             'pmd_since': '1.0'},
 'PMD_ADLIBDC': {'pmd_category': 'basic',
                 'pmd_name': 'AvoidDecimalLiteralsInBigDecimalConstructor',
                 'pmd_since': '3.4'},
 'PMD_ADS': {'pmd_category': 'naming',
             'pmd_name': 'AvoidDollarSigns',
             'pmd_since': '1.5'},
 'PMD_AES': {'pmd_category': 'optimizations',
             'pmd_name': 'AddEmptyString',
             'pmd_since': '4.0'},
 'PMD_AFNMMN': {'pmd_category': 'naming',
                'pmd_name': 'AvoidFieldNameMatchingMethodName',
                'pmd_since': '3.0'},
 'PMD_AFNMTN': {'pmd_category': 'naming',
                'pmd_name': 'AvoidFieldNameMatchingTypeName',
                'pmd_since': '3.0'},
 'PMD_AICICC': {'pmd_category': 'design',
                'pmd_name': 'AvoidInstanceofChecksInCatchClause',
                'pmd_since': '3.0'},
 'PMD_AIO': {'pmd_category': 'controversial',
             'pmd_name': 'AssignmentInOperand',
             'pmd_since': '1.03'},
 'PMD_AISD': {'pmd_category': 'sunsecure',
              'pmd_name': 'ArrayIsStoredDirectly',
              'pmd_since': '2.2'},
 'PMD_ALEI': {'pmd_category': 'strictexception',
              'pmd_name': 'AvoidLosingExceptionInformation',
              'pmd_since': '4.2.6'},
 'PMD_AMUO': {'pmd_category': 'basic',
              'pmd_name': 'AvoidMultipleUnaryOperators',
              'pmd_since': '4.2'},
 'PMD_APFIFC': {'pmd_category': 'design',
                'pmd_name': 'AvoidProtectedFieldInFinalClass',
                'pmd_since': '2.1'},
 'PMD_APMIFCNE': {'pmd_category': 'design',
                  'pmd_name': 'AvoidProtectedMethodInFinalClassNotExtending',
                  'pmd_since': '5.1'},
 'PMD_APMP': {'pmd_category': 'controversial',
              'pmd_name': 'AvoidPrefixingMethodParameters',
              'pmd_since': '5.0'},
 'PMD_APST': {'pmd_category': 'logging-java',
              'pmd_name': 'AvoidPrintStackTrace',
              'pmd_since': '3.2'},
 'PMD_ARE': {'pmd_category': 'strictexception',
             'pmd_name': 'AvoidRethrowingException',
             'pmd_since': '3.8'},
 'PMD_ARP': {'pmd_category': 'design',
             'pmd_name': 'AvoidReassigningParameters',
             'pmd_since': '1.0'},
 'PMD_ASAML': {'pmd_category': 'design',
               'pmd_name': 'AvoidSynchronizedAtMethodLevel',
               'pmd_since': '3.0'},
 'PMD_ASBF': {'pmd_category': 'strings',
              'pmd_name': 'AvoidStringBufferField',
              'pmd_since': '4.2'},
 'PMD_ATG': {'pmd_category': 'basic',
             'pmd_name': 'AvoidThreadGroup',
             'pmd_since': '3.6'},
 'PMD_ATNFS': {'pmd_category': 'design',
               'pmd_name': 'AssignmentToNonFinalStatic',
               'pmd_since': '2.2'},
 'PMD_ATNIOSE': {'pmd_category': 'strictexception',
                 'pmd_name': 'AvoidThrowingNewInstanceOfSameException',
                 'pmd_since': '4.2.5'},
 'PMD_ATNPE': {'pmd_category': 'strictexception',
               'pmd_name': 'AvoidThrowingNullPointerException',
               'pmd_since': '1.8'},
 'PMD_ATRET': {'pmd_category': 'strictexception',
               'pmd_name': 'AvoidThrowingRawExceptionTypes',
               'pmd_since': '1.8'},
 'PMD_AUHCIP': {'pmd_category': 'basic',
                'pmd_name': 'AvoidUsingHardCodedIP',
                'pmd_since': '4.1'},
 'PMD_AUNC': {'pmd_category': 'controversial',
              'pmd_name': 'AvoidUsingNativeCode',
              'pmd_since': '4.1'},
 'PMD_AUOV': {'pmd_category': 'basic',
              'pmd_name': 'AvoidUsingOctalValues',
              'pmd_since': '3.9'},
 'PMD_AbCWAM': {'pmd_category': 'design',
                'pmd_name': 'AbstractClassWithoutAnyMethod',
                'pmd_since': '4.2'},
 'PMD_BC': {'pmd_category': 'design',
            'pmd_name': 'BadComparison',
            'pmd_since': '1.8'},
 'PMD_BGMN': {'pmd_category': 'naming',
              'pmd_name': 'BooleanGetMethodName',
              'pmd_since': '4.0'},
 'PMD_BI': {'pmd_category': 'basic',
            'pmd_name': 'BooleanInstantiation',
            'pmd_since': '1.2'},
 'PMD_BII': {'pmd_category': 'basic',
             'pmd_name': 'BigIntegerInstantiation',
             'pmd_since': '3.9'},
 'PMD_BNC': {'pmd_category': 'basic',
             'pmd_name': 'BrokenNullCheck',
             'pmd_since': '3.8'},
 'PMD_CASR': {'pmd_category': 'strings',
              'pmd_name': 'ConsecutiveAppendsShouldReuse',
              'pmd_since': '5.1'},
 'PMD_CCEWTA': {'pmd_category': 'basic',
                'pmd_name': 'ClassCastExceptionWithToArray',
                'pmd_since': '3.4'},
 'PMD_CCOM': {'pmd_category': 'design',
              'pmd_name': 'ConstructorCallsOverridableMethod',
              'pmd_since': '1.04'},
 'PMD_CIS': {'pmd_category': 'basic',
             'pmd_name': 'CollapsibleIfStatements',
             'pmd_since': '3.1'},
 'PMD_CLA': {'pmd_category': 'strings',
             'pmd_name': 'ConsecutiveLiteralAppends',
             'pmd_since': '3.5'},
 'PMD_CNC': {'pmd_category': 'naming',
             'pmd_name': 'ClassNamingConventions',
             'pmd_since': '1.2'},
 'PMD_CRS': {'pmd_category': 'basic',
             'pmd_name': 'CheckResultSet',
             'pmd_since': '4.1'},
 'PMD_CSR': {'pmd_category': 'basic',
             'pmd_name': 'CheckSkipResult',
             'pmd_since': '5.0'},
 'PMD_CTCNSE': {'pmd_category': 'clone',
                'pmd_name': 'CloneThrowsCloneNotSupportedException',
                'pmd_since': '1.9'},
 'PMD_CWOPCSBF': {'pmd_category': 'design',
                  'pmd_name': 'ClassWithOnlyPrivateConstructorsShouldBeFinal',
                  'pmd_since': '4.1'},
 'PMD_ClMMIC': {'pmd_category': 'typeresolution',
                'pmd_name': 'CloneMethodMustImplementCloneable',
                'pmd_since': '3.9'},
 'PMD_ClR': {'pmd_category': 'design',
             'pmd_name': 'CloseResource',
             'pmd_since': '1.2.2'},
 'PMD_DCL': {'pmd_category': 'basic',
             'pmd_name': 'DoubleCheckedLocking',
             'pmd_since': '1.04'},
 'PMD_DCTR': {'pmd_category': 'basic',
              'pmd_name': 'DontCallThreadRun',
              'pmd_since': '4.3'},
 'PMD_DI': {'pmd_category': 'imports',
            'pmd_name': 'DuplicateImports',
            'pmd_since': '0.5'},
 'PMD_DIJL': {'pmd_category': 'imports',
              'pmd_name': 'DontImportJavaLang',
              'pmd_since': '0.5'},
 'PMD_DIS': {'pmd_category': 'controversial',
             'pmd_name': 'DontImportSun',
             'pmd_since': '1.5'},
 'PMD_DLNLISS': {'pmd_category': 'design',
                 'pmd_name': 'DefaultLabelNotLastInSwitchStmt',
                 'pmd_since': '1.5'},
 'PMD_DNCGCE': {'pmd_category': 'controversial',
                'pmd_name': 'DoNotCallGarbageCollectionExplicitly',
                'pmd_since': '4.2'},
 'PMD_DNCSE': {'pmd_category': 'j2ee',
               'pmd_name': 'DoNotCallSystemExit',
               'pmd_since': '4.1'},
 'PMD_DNEJLE': {'pmd_category': 'strictexception',
                'pmd_name': 'DoNotExtendJavaLangError',
                'pmd_since': '4.0'},
 'PMD_DNTEIF': {'pmd_category': 'strictexception',
                'pmd_name': 'DoNotThrowExceptionInFinally',
                'pmd_since': '4.2'},
 'PMD_DP': {'pmd_category': 'controversial',
            'pmd_name': 'DefaultPackage',
            'pmd_since': '3.4'},
 'PMD_DUFTFLI': {'pmd_category': 'basic',
                 'pmd_name': 'DontUseFloatTypeForLoopIndices',
                 'pmd_since': '4.3'},
 'PMD_EAFC': {'pmd_category': 'strictexception',
              'pmd_name': 'ExceptionAsFlowControl',
              'pmd_since': '1.8'},
 'PMD_ECB': {'pmd_category': 'empty',
             'pmd_name': 'EmptyCatchBlock',
             'pmd_since': '0.1'},
 'PMD_EF': {'pmd_category': 'finalizers',
            'pmd_name': 'EmptyFinalizer',
            'pmd_since': '1.5'},
 'PMD_EFB': {'pmd_category': 'empty',
             'pmd_name': 'EmptyFinallyBlock',
             'pmd_since': '0.4'},
 'PMD_EIS': {'pmd_category': 'empty',
             'pmd_name': 'EmptyIfStmt',
             'pmd_since': '0.1'},
 'PMD_EMIACSBA': {'pmd_category': 'design',
                  'pmd_name': 'EmptyMethodInAbstractClassShouldBeAbstract',
                  'pmd_since': '4.1'},
 'PMD_EN': {'pmd_category': 'design',
            'pmd_name': 'EqualsNull',
            'pmd_since': '1.9'},
 'PMD_EO': {'pmd_category': 'basic',
            'pmd_name': 'ExtendsObject',
            'pmd_since': '5.0'},
 'PMD_ESB': {'pmd_category': 'empty',
             'pmd_name': 'EmptySynchronizedBlock',
             'pmd_since': '1.3'},
 'PMD_ESI': {'pmd_category': 'empty',
             'pmd_name': 'EmptyStaticInitializer',
             'pmd_since': '1.5'},
 'PMD_ESNIL': {'pmd_category': 'empty',
               'pmd_name': 'EmptyStatementNotInLoop',
               'pmd_since': '1.5'},
 'PMD_ESS': {'pmd_category': 'empty',
             'pmd_name': 'EmptySwitchStatements',
             'pmd_since': '1.0'},
 'PMD_ETB': {'pmd_category': 'empty',
             'pmd_name': 'EmptyTryBlock',
             'pmd_since': '0.4'},
 'PMD_EWS': {'pmd_category': 'empty',
             'pmd_name': 'EmptyWhileStmt',
             'pmd_since': '0.2'},
 'PMD_EmSB': {'pmd_category': 'empty',
              'pmd_name': 'EmptyStatementBlock',
              'pmd_since': '5.0'},
 'PMD_FDNCSF': {'pmd_category': 'finalizers',
                'pmd_name': 'FinalizeDoesNotCallSuperFinalize',
                'pmd_since': '1.5'},
 'PMD_FDSBASOC': {'pmd_category': 'design',
                  'pmd_name': 'FieldDeclarationsShouldBeAtStartOfClass',
                  'pmd_since': '5.0'},
 'PMD_FFCBS': {'pmd_category': 'design',
               'pmd_name': 'FinalFieldCouldBeStatic',
               'pmd_since': '1.1'},
 'PMD_FLMUB': {'pmd_category': 'braces',
               'pmd_name': 'ForLoopsMustUseBraces',
               'pmd_since': '0.7'},
 'PMD_FLSBWL': {'pmd_category': 'basic',
                'pmd_name': 'ForLoopShouldBeWhileLoop',
                'pmd_since': '1.02'},
 'PMD_FO': {'pmd_category': 'finalizers',
            'pmd_name': 'FinalizeOverloaded',
            'pmd_since': '1.5'},
 'PMD_FOCSF': {'pmd_category': 'finalizers',
               'pmd_name': 'FinalizeOnlyCallsSuperFinalize',
               'pmd_since': '1.5'},
 'PMD_FSBP': {'pmd_category': 'finalizers',
              'pmd_name': 'FinalizeShouldBeProtected',
              'pmd_since': '1.1'},
 'PMD_GDL': {'pmd_category': 'logging-jakarta-commons',
             'pmd_name': 'GuardDebugLogging',
             'pmd_since': '4.3'},
 'PMD_GLS': {'pmd_category': 'logging-jakarta-commons',
             'pmd_name': 'GuardLogStatement',
             'pmd_since': '5.1.0'},
 'PMD_GLSJU': {'pmd_category': 'logging-java',
               'pmd_name': 'GuardLogStatementJavaUtil',
               'pmd_since': '5.1.0'},
 'PMD_GN': {'pmd_category': 'naming',
            'pmd_name': 'GenericsNaming',
            'pmd_since': '4.2.6'},
 'PMD_IESMUB': {'pmd_category': 'braces',
                'pmd_name': 'IfElseStmtsMustUseBraces',
                'pmd_since': '0.2'},
 'PMD_IF': {'pmd_category': 'design',
            'pmd_name': 'ImmutableField',
            'pmd_since': '2.0'},
 'PMD_IFSP': {'pmd_category': 'imports',
              'pmd_name': 'ImportFromSamePackage',
              'pmd_since': '1.02'},
 'PMD_IO': {'pmd_category': 'design',
            'pmd_name': 'IdempotentOperations',
            'pmd_since': '2.0'},
 'PMD_ISB': {'pmd_category': 'strings',
             'pmd_name': 'InefficientStringBuffering',
             'pmd_since': '3.4'},
 'PMD_ISMUB': {'pmd_category': 'braces',
               'pmd_name': 'IfStmtsMustUseBraces',
               'pmd_since': '1.0'},
 'PMD_ITGC': {'pmd_category': 'design',
              'pmd_name': 'InstantiationToGetClass',
              'pmd_since': '2.0'},
 'PMD_JI': {'pmd_category': 'basic',
            'pmd_name': 'JumbledIncrementer',
            'pmd_since': '1.0'},
 'PMD_JUASIM': {'pmd_category': 'junit',
                'pmd_name': 'JUnitAssertionsShouldIncludeMessage',
                'pmd_since': '1.04'},
 'PMD_JUS': {'pmd_category': 'junit',
             'pmd_name': 'JUnitSpelling',
             'pmd_since': '1.0'},
 'PMD_JUSS': {'pmd_category': 'junit',
              'pmd_name': 'JUnitStaticSuite',
              'pmd_since': '1.0'},
 'PMD_JUTCTMA': {'pmd_category': 'junit',
                 'pmd_name': 'JUnitTestContainsTooManyAsserts',
                 'pmd_since': '5.0'},
 'PMD_JUTSIA': {'pmd_category': 'junit',
                'pmd_name': 'JUnitTestsShouldIncludeAssert',
                'pmd_since': '2.0'},
 'PMD_LHNC': {'pmd_category': 'j2ee',
              'pmd_name': 'LocalHomeNamingConvention',
              'pmd_since': '4.0'},
 'PMD_LI': {'pmd_category': 'design',
            'pmd_name': 'LogicInversion',
            'pmd_since': '5.0'},
 'PMD_LINSF': {'pmd_category': 'logging-java',
               'pmd_name': 'LoggerIsNotStaticFinal',
               'pmd_since': '2.0'},
 'PMD_LISNC': {'pmd_category': 'j2ee',
               'pmd_name': 'LocalInterfaceSessionNamingConvention',
               'pmd_since': '4.0'},
 'PMD_LoC': {'pmd_category': 'typeresolution',
             'pmd_name': 'LooseCoupling',
             'pmd_since': '3.9'},
 'PMD_MBIS': {'pmd_category': 'design',
              'pmd_name': 'MissingBreakInSwitch',
              'pmd_since': '3.0'},
 'PMD_MDBASBNC': {'pmd_category': 'j2ee',
                  'pmd_name': 'MDBAndSessionBeanNamingConvention',
                  'pmd_since': '4.0'},
 'PMD_MNC': {'pmd_category': 'basic',
             'pmd_name': 'MisplacedNullCheck',
             'pmd_since': '3.5'},
 'PMD_MRIA': {'pmd_category': 'sunsecure',
              'pmd_name': 'MethodReturnsInternalArray',
              'pmd_since': '2.2'},
 'PMD_MSMINIC': {'pmd_category': 'design',
                 'pmd_name': 'MissingStaticMethodInNonInstantiatableClass',
                 'pmd_since': '3.0'},
 'PMD_MSVUID': {'pmd_category': 'javabeans',
                'pmd_name': 'MissingSerialVersionUID',
                'pmd_since': '3.0'},
 'PMD_MTOL': {'pmd_category': 'logging-java',
              'pmd_name': 'MoreThanOneLogger',
              'pmd_since': '2.0'},
 'PMD_MWSNAEC': {'pmd_category': 'naming',
                 'pmd_name': 'MethodWithSameNameAsEnclosingClass',
                 'pmd_since': '1.5'},
 'PMD_MeNC': {'pmd_category': 'naming',
              'pmd_name': 'MethodNamingConventions',
              'pmd_since': '1.2'},
 'PMD_NCLISS': {'pmd_category': 'design',
                'pmd_name': 'NonCaseLabelInSwitchStatement',
                'pmd_since': '1.5'},
 'PMD_NP': {'pmd_category': 'naming',
            'pmd_name': 'NoPackage',
            'pmd_since': '3.3'},
 'PMD_NSI': {'pmd_category': 'design',
             'pmd_name': 'NonStaticInitializer',
             'pmd_since': '1.5'},
 'PMD_NTSS': {'pmd_category': 'design',
              'pmd_name': 'NonThreadSafeSingleton',
              'pmd_since': '3.4'},
 'PMD_OBEAH': {'pmd_category': 'basic',
               'pmd_name': 'OverrideBothEqualsAndHashcode',
               'pmd_since': '0.4'},
 'PMD_ODPL': {'pmd_category': 'controversial',
              'pmd_name': 'OneDeclarationPerLine',
              'pmd_since': '5.0'},
 'PMD_OTAC': {'pmd_category': 'design',
              'pmd_name': 'OptimizableToArrayCall',
              'pmd_since': '1.8'},
 'PMD_PC': {'pmd_category': 'naming',
            'pmd_name': 'PackageCase',
            'pmd_since': '3.3'},
 'PMD_PCI': {'pmd_category': 'clone',
             'pmd_name': 'ProperCloneImplementation',
             'pmd_since': '1.4'},
 'PMD_PL': {'pmd_category': 'logging-jakarta-commons',
            'pmd_name': 'ProperLogger',
            'pmd_since': '3.3'},
 'PMD_PLFIC': {'pmd_category': 'design',
               'pmd_name': 'PositionLiteralsFirstInComparisons',
               'pmd_since': '3.3'},
 'PMD_PLFICIC': {'pmd_category': 'design',
                 'pmd_name': 'PositionLiteralsFirstInCaseInsensitiveComparisons',
                 'pmd_since': '5.1'},
 'PMD_PST': {'pmd_category': 'design',
             'pmd_name': 'PreserveStackTrace',
             'pmd_since': '3.7'},
 'PMD_REARTN': {'pmd_category': 'design',
                'pmd_name': 'ReturnEmptyArrayRatherThanNull',
                'pmd_since': '4.2'},
 'PMD_RFFB': {'pmd_category': 'basic',
              'pmd_name': 'ReturnFromFinallyBlock',
              'pmd_since': '1.05'},
 'PMD_RFI': {'pmd_category': 'optimizations',
             'pmd_name': 'RedundantFieldInitializer',
             'pmd_since': '5.0'},
 'PMD_RINC': {'pmd_category': 'j2ee',
              'pmd_name': 'RemoteInterfaceNamingConvention',
              'pmd_since': '4.0'},
 'PMD_RSINC': {'pmd_category': 'j2ee',
               'pmd_name': 'RemoteSessionInterfaceNamingConvention',
               'pmd_since': '4.0'},
 'PMD_SBA': {'pmd_category': 'junit',
             'pmd_name': 'SimplifyBooleanAssertion',
             'pmd_since': '3.6'},
 'PMD_SBE': {'pmd_category': 'design',
             'pmd_name': 'SimplifyBooleanExpressions',
             'pmd_since': '1.05'},
 'PMD_SBIWC': {'pmd_category': 'strings',
               'pmd_name': 'StringBufferInstantiationWithChar',
               'pmd_since': '3.9'},
 'PMD_SBR': {'pmd_category': 'design',
             'pmd_name': 'SimplifyBooleanReturns',
             'pmd_since': '0.9'},
 'PMD_SC': {'pmd_category': 'design',
            'pmd_name': 'SimplifyConditional',
            'pmd_since': '3.1'},
 'PMD_SCFN': {'pmd_category': 'naming',
              'pmd_name': 'SuspiciousConstantFieldName',
              'pmd_since': '2.0'},
 'PMD_SCN': {'pmd_category': 'naming',
             'pmd_name': 'ShortClassName',
             'pmd_since': '5.0'},
 'PMD_SDFNL': {'pmd_category': 'design',
               'pmd_name': 'SimpleDateFormatNeedsLocale',
               'pmd_since': '2.0'},
 'PMD_SEJBFSBF': {'pmd_category': 'j2ee',
                  'pmd_name': 'StaticEJBFieldShouldBeFinal',
                  'pmd_since': '4.1'},
 'PMD_SEMN': {'pmd_category': 'naming',
              'pmd_name': 'SuspiciousEqualsMethodName',
              'pmd_since': '2.0'},
 'PMD_SF': {'pmd_category': 'design',
            'pmd_name': 'SingularField',
            'pmd_since': '3.1'},
 'PMD_SHMN': {'pmd_category': 'naming',
              'pmd_name': 'SuspiciousHashcodeMethodName',
              'pmd_since': '1.5'},
 'PMD_SMN': {'pmd_category': 'naming',
             'pmd_name': 'ShortMethodName',
             'pmd_since': '0.3'},
 'PMD_SOE': {'pmd_category': 'controversial',
             'pmd_name': 'SuspiciousOctalEscape',
             'pmd_since': '1.5'},
 'PMD_SP': {'pmd_category': 'logging-java',
            'pmd_name': 'SystemPrintln',
            'pmd_since': '2.1'},
 'PMD_SSSHD': {'pmd_category': 'design',
               'pmd_name': 'SwitchStmtsShouldHaveDefault',
               'pmd_since': '1.0'},
 'PMD_STS': {'pmd_category': 'strings',
             'pmd_name': 'StringToString',
             'pmd_since': '1.0'},
 'PMD_SiDTE': {'pmd_category': 'typeresolution',
               'pmd_name': 'SignatureDeclareThrowsException',
               'pmd_since': '4.0'},
 'PMD_StI': {'pmd_category': 'strings',
             'pmd_name': 'StringInstantiation',
             'pmd_since': '1.0'},
 'PMD_TCWTC': {'pmd_category': 'junit',
               'pmd_name': 'TestClassWithoutTestCases',
               'pmd_since': '3.0'},
 'PMD_TFBFASS': {'pmd_category': 'design',
                 'pmd_name': 'TooFewBranchesForASwitchStatement',
                 'pmd_since': '4.2'},
 'PMD_TMSI': {'pmd_category': 'imports',
              'pmd_name': 'TooManyStaticImports',
              'pmd_since': '4.1'},
 'PMD_UAAL': {'pmd_category': 'optimizations',
              'pmd_name': 'UseArraysAsList',
              'pmd_since': '3.5'},
 'PMD_UAEIOAT': {'pmd_category': 'junit',
                 'pmd_name': 'UseAssertEqualsInsteadOfAssertTrue',
                 'pmd_since': '3.1'},
 'PMD_UALIOV': {'pmd_category': 'optimizations',
                'pmd_name': 'UseArrayListInsteadOfVector',
                'pmd_since': '3.0'},
 'PMD_UANIOAT': {'pmd_category': 'junit',
                 'pmd_name': 'UseAssertNullInsteadOfAssertTrue',
                 'pmd_since': '3.5'},
 'PMD_UASIOAT': {'pmd_category': 'junit',
                 'pmd_name': 'UseAssertSameInsteadOfAssertTrue',
                 'pmd_since': '3.1'},
 'PMD_UATIOAE': {'pmd_category': 'junit',
                 'pmd_name': 'UseAssertTrueInsteadOfAssertEquals',
                 'pmd_since': '5.0'},
 'PMD_UBA': {'pmd_category': 'junit',
             'pmd_name': 'UnnecessaryBooleanAssertion',
             'pmd_since': '3.0'},
 'PMD_UC': {'pmd_category': 'controversial',
            'pmd_name': 'UnnecessaryConstructor',
            'pmd_since': '1.0'},
 'PMD_UCC': {'pmd_category': 'strings',
             'pmd_name': 'UnnecessaryCaseChange',
             'pmd_since': '3.3'},
 'PMD_UCEL': {'pmd_category': 'logging-jakarta-commons',
              'pmd_name': 'UseCorrectExceptionLogging',
              'pmd_since': '3.2'},
 'PMD_UCIE': {'pmd_category': 'design',
              'pmd_name': 'UseCollectionIsEmpty',
              'pmd_since': '3.9'},
 'PMD_UCT': {'pmd_category': 'unnecessary',
             'pmd_name': 'UnnecessaryConversionTemporary',
             'pmd_since': '0.1'},
 'PMD_UEC': {'pmd_category': 'design',
             'pmd_name': 'UncommentedEmptyConstructor',
             'pmd_since': '3.4'},
 'PMD_UEM': {'pmd_category': 'design',
             'pmd_name': 'UncommentedEmptyMethod',
             'pmd_since': '3.4'},
 'PMD_UETCS': {'pmd_category': 'strings',
               'pmd_name': 'UseEqualsToCompareStrings',
               'pmd_since': '4.1'},
 'PMD_UFQN': {'pmd_category': 'imports',
              'pmd_name': 'UnnecessaryFullyQualifiedName',
              'pmd_since': '5.0'},
 'PMD_UIS': {'pmd_category': 'basic',
             'pmd_name': 'UnconditionalIfStatement',
             'pmd_since': '1.5'},
 'PMD_ULBR': {'pmd_category': 'design',
              'pmd_name': 'UnnecessaryLocalBeforeReturn',
              'pmd_since': '3.3'},
 'PMD_ULV': {'pmd_category': 'unusedcode',
             'pmd_name': 'UnusedLocalVariable',
             'pmd_since': '0.1'},
 'PMD_ULWCC': {'pmd_category': 'design',
               'pmd_name': 'UseLocaleWithCaseConversions',
               'pmd_since': '2.0'},
 'PMD_UNAION': {'pmd_category': 'design',
                'pmd_name': 'UseNotifyAllInsteadOfNotify',
                'pmd_since': '3.0'},
 'PMD_UNCIE': {'pmd_category': 'unnecessary',
               'pmd_name': 'UnusedNullCheckInEquals',
               'pmd_since': '3.5'},
 'PMD_UOM': {'pmd_category': 'unnecessary',
             'pmd_name': 'UselessOverridingMethod',
             'pmd_since': '3.3'},
 'PMD_UOOI': {'pmd_category': 'unnecessary',
              'pmd_name': 'UselessOperationOnImmutable',
              'pmd_since': '3.5'},
 'PMD_UPF': {'pmd_category': 'unusedcode',
             'pmd_name': 'UnusedPrivateField',
             'pmd_since': '0.1'},
 'PMD_UPM': {'pmd_category': 'unusedcode',
             'pmd_name': 'UnusedPrivateMethod',
             'pmd_since': '0.7'},
 'PMD_USBFSA': {'pmd_category': 'optimizations',
                'pmd_name': 'UseStringBufferForStringAppends',
                'pmd_since': '3.1'},
 'PMD_USDF': {'pmd_category': 'design',
              'pmd_name': 'UnsynchronizedStaticDateFormatter',
              'pmd_since': '3.6'},
 'PMD_UV': {'pmd_category': 'design',
            'pmd_name': 'UseVarargs',
            'pmd_since': '5.0'},
 'PMD_UWOC': {'pmd_category': 'optimizations',
              'pmd_name': 'UnnecessaryWrapperObjectCreation',
              'pmd_since': '3.8'},
 'PMD_UnI': {'pmd_category': 'typeresolution',
             'pmd_name': 'UnusedImports',
             'pmd_since': '4.0'},
 'PMD_VNC': {'pmd_category': 'naming',
             'pmd_name': 'VariableNamingConventions',
             'pmd_since': '1.2'},
 'PMD_WLMUB': {'pmd_category': 'braces',
               'pmd_name': 'WhileLoopsMustUseBraces',
               'pmd_since': '0.7'}}

DEFAULT_RULES_MAVEN_CLEANED = ['PMD_AUHCIP', 'PMD_CRS', 'PMD_UnI', 'PMD_ULV', 'PMD_UPF', 'PMD_UPM', 'PMD_DIJL', 'PMD_DI', 'PMD_EO', 'PMD_FLSBWL', 'PMD_TMSI', 'PMD_UFQN', 'PMD_CIS', 'PMD_UOM', 'PMD_ABSALIL', 'PMD_ADLIBDC', 'PMD_AMUO', 'PMD_AUOV', 'PMD_BNC', 'PMD_CSR', 'PMD_CCEWTA', 'PMD_DUFTFLI', 'PMD_ECB', 'PMD_EFB', 'PMD_EIS', 'PMD_EmSB', 'PMD_ESNIL', 'PMD_ESS', 'PMD_ESB', 'PMD_ETB', 'PMD_EWS', 'PMD_IFSP', 'PMD_JI', 'PMD_MNC', 'PMD_OBEAH', 'PMD_RFFB', 'PMD_UIS', 'PMD_UCT', 'PMD_UNCIE', 'PMD_UOOI', 'PMD_ATG', 'PMD_DCTR', 'PMD_DCL', 'PMD_BII', 'PMD_BI']

# taken from https://gitbox.apache.org/repos/asf?p=maven-pmd-plugin.git;a=blob_plain;f=src/main/resources/rulesets/java/maven-pmd-plugin-default.xml;hb=HEAD
DEFAULT_RULES_MAVEN = ['AvoidUsingHardCodedIP',
 'CheckResultSet',
 'UnusedImports',
 'UnusedFormalParameter',
 'UnusedLocalVariable',
 'UnusedPrivateField',
 'UnusedPrivateMethod',
 'DontImportJavaLang',
 'DuplicateImports',
 'ExtendsObject',
 'ForLoopShouldBeWhileLoop',
 'TooManyStaticImports',
 'UnnecessaryFullyQualifiedName',
 'UnnecessaryModifier',
 'UnnecessaryReturn',
 'UselessParentheses',
 'UselessQualifiedThis',
 'CollapsibleIfStatements',
 'SimplifiedTernary',
 'UselessOverridingMethod',
 'AvoidBranchingStatementAsLastInLoop',
 'AvoidDecimalLiteralsInBigDecimalConstructor',
 'AvoidMultipleUnaryOperators',
 'AvoidUsingOctalValues',
 'BrokenNullCheck',
 'CheckSkipResult',
 'ClassCastExceptionWithToArray',
 'DontUseFloatTypeForLoopIndices',
 'EmptyCatchBlock',
 'EmptyFinallyBlock',
 'EmptyIfStmt',
 'EmptyInitializer',
 'EmptyStatementBlock',
 'EmptyStatementNotInLoop',
 'EmptySwitchStatements',
 'EmptySynchronizedBlock',
 'EmptyTryBlock',
 'EmptyWhileStmt',
 'ImportFromSamePackage',
 'JumbledIncrementer',
 'MisplacedNullCheck',
 'OverrideBothEqualsAndHashcode',
 'ReturnFromFinallyBlock',
 'UnconditionalIfStatement',
 'UnnecessaryConversionTemporary',
 'UnusedNullCheckInEquals',
 'UselessOperationOnImmutable',
 'AvoidThreadGroup',
 'DontCallThreadRun',
 'DoubleCheckedLocking',
 'BigIntegerInstantiation',
 'BooleanInstantiation']

# mapping of pmd name to sourcemeter name
PMD_NAME_TO_SM = {v['pmd_name']: k for k, v in PMD_RULES_SINCE.items()}

# all deprecated rulesets, source: https://pmd.github.io/pmd-6.12.0/pmd_rules_java.html#additional-rulesets
PMD_OLD_RULESETS = {'android': 'CallSuperFirst, CallSuperLast, DoNotHardCodeSDCard',
                    'basic': 'AvoidBranchingStatementAsLastInLoop, AvoidDecimalLiteralsInBigDecimalConstructor, AvoidMultipleUnaryOperators, AvoidThreadGroup, AvoidUsingHardCodedIP, AvoidUsingOctalValues, BigIntegerInstantiation, BooleanInstantiation, BrokenNullCheck, CheckResultSet, CheckSkipResult, ClassCastExceptionWithToArray, CollapsibleIfStatements, DontCallThreadRun, DontUseFloatTypeForLoopIndices, DoubleCheckedLocking, ExtendsObject, ForLoopShouldBeWhileLoop, JumbledIncrementer, MisplacedNullCheck, OverrideBothEqualsAndHashcode, ReturnFromFinallyBlock, SimplifiedTernary, UnconditionalIfStatement',
                    'braces': 'ForLoopsMustUseBraces, IfElseStmtsMustUseBraces, IfStmtsMustUseBraces, WhileLoopsMustUseBraces',
                    'clone': 'CloneMethodMustBePublic, CloneMethodMustImplementCloneable, CloneMethodReturnTypeMustMatchClassName, CloneThrowsCloneNotSupportedException, ProperCloneImplementation',
                    'codesize': 'CyclomaticComplexity, ExcessiveClassLength, ExcessiveMethodLength, ExcessiveParameterList, ExcessivePublicCount, ModifiedCyclomaticComplexity, NcssConstructorCount, NcssCount, NcssMethodCount, NcssTypeCount, NPathComplexity, StdCyclomaticComplexity, TooManyFields, TooManyMethods',
                    'comments': 'CommentContent, CommentDefaultAccessModifier, CommentRequired, CommentSize',
                    'controversial': 'AssignmentInOperand, AtLeastOneConstructor, AvoidAccessibilityAlteration, AvoidFinalLocalVariable, AvoidLiteralsInIfCondition, AvoidPrefixingMethodParameters, AvoidUsingNativeCode, AvoidUsingShortType, AvoidUsingVolatile, CallSuperInConstructor, DataflowAnomalyAnalysis, DefaultPackage, DoNotCallGarbageCollectionExplicitly, DontImportSun, NullAssignment, OneDeclarationPerLine, OnlyOneReturn, SuspiciousOctalEscape, UnnecessaryConstructor, UnnecessaryParentheses, UseConcurrentHashMap, UseObjectForClearerAPI',
                    'coupling': 'CouplingBetweenObjects, ExcessiveImports, LawOfDemeter, LooseCoupling, LoosePackageCoupling',
                    'design': 'AbstractClassWithoutAbstractMethod, AbstractClassWithoutAnyMethod, AccessorClassGeneration, AccessorMethodGeneration, AssignmentToNonFinalStatic, AvoidDeeplyNestedIfStmts, AvoidInstanceofChecksInCatchClause, AvoidProtectedFieldInFinalClass, AvoidProtectedMethodInFinalClassNotExtending, AvoidReassigningParameters, AvoidSynchronizedAtMethodLevel, BadComparison, ClassWithOnlyPrivateConstructorsShouldBeFinal, CloseResource, CompareObjectsWithEquals, ConfusingTernary, ConstantsInInterface, ConstructorCallsOverridableMethod, DataClass, DefaultLabelNotLastInSwitchStmt, EmptyMethodInAbstractClassShouldBeAbstract, EqualsNull, FieldDeclarationsShouldBeAtStartOfClass, FinalFieldCouldBeStatic, GodClass, IdempotentOperations, ImmutableField, InstantiationToGetClass, LogicInversion, MissingBreakInSwitch, MissingStaticMethodInNonInstantiatableClass, NonCaseLabelInSwitchStatement, NonStaticInitializer, NonThreadSafeSingleton, OptimizableToArrayCall, PositionLiteralsFirstInCaseInsensitiveComparisons, PositionLiteralsFirstInComparisons, PreserveStackTrace, ReturnEmptyArrayRatherThanNull, SimpleDateFormatNeedsLocale, SimplifyBooleanExpressions, SimplifyBooleanReturns, SimplifyConditional, SingleMethodSingleton, SingletonClassReturningNewInstance, SingularField, SwitchDensity, SwitchStmtsShouldHaveDefault, TooFewBranchesForASwitchStatement, UncommentedEmptyConstructor, UncommentedEmptyMethodBody, UnnecessaryLocalBeforeReturn, UnsynchronizedStaticDateFormatter, UseCollectionIsEmpty, UseLocaleWithCaseConversions, UseNotifyAllInsteadOfNotify, UseUtilityClass, UseVarargs',
                    'empty': 'EmptyCatchBlock, EmptyFinallyBlock, EmptyIfStmt, EmptyInitializer, EmptyStatementBlock, EmptyStatementNotInLoop, EmptyStaticInitializer, EmptySwitchStatements, EmptySynchronizedBlock, EmptyTryBlock, EmptyWhileStmt',
                    'finalizers': 'AvoidCallingFinalize, EmptyFinalizer, FinalizeDoesNotCallSuperFinalize, FinalizeOnlyCallsSuperFinalize, FinalizeOverloaded, FinalizeShouldBeProtected',
                    'imports': 'DontImportJavaLang, DuplicateImports, ImportFromSamePackage, TooManyStaticImports, UnnecessaryFullyQualifiedName, UnusedImports',
                    'j2ee': 'DoNotCallSystemExit, DoNotUseThreads, LocalHomeNamingConvention, LocalInterfaceSessionNamingConvention, MDBAndSessionBeanNamingConvention, RemoteInterfaceNamingConvention, RemoteSessionInterfaceNamingConvention, StaticEJBFieldShouldBeFinal, UseProperClassLoader',
                    'javabeans': 'BeanMembersShouldSerialize, MissingSerialVersionUID',
                    'junit': 'JUnitAssertionsShouldIncludeMessage, JUnitSpelling, JUnitStaticSuite, JUnitTestContainsTooManyAsserts, JUnitTestsShouldIncludeAssert, SimplifyBooleanAssertion, TestClassWithoutTestCases, UnnecessaryBooleanAssertion, UseAssertEqualsInsteadOfAssertTrue, UseAssertNullInsteadOfAssertTrue, UseAssertSameInsteadOfAssertTrue, UseAssertTrueInsteadOfAssertEquals',
                    'metrics': 'CyclomaticComplexity',
                    'migrating_to_junit4': 'JUnit4SuitesShouldUseSuiteAnnotation, JUnit4TestShouldUseAfterAnnotation, JUnit4TestShouldUseBeforeAnnotation, JUnit4TestShouldUseTestAnnotation, JUnitUseExpected',
                    'migrating': 'AvoidAssertAsIdentifier, AvoidEnumAsIdentifier, ByteInstantiation, ForLoopCanBeForeach, IntegerInstantiation, JUnit4SuitesShouldUseSuiteAnnotation, JUnit4TestShouldUseAfterAnnotation, JUnit4TestShouldUseBeforeAnnotation, JUnit4TestShouldUseTestAnnotation, JUnitUseExpected, LongInstantiation, ReplaceEnumerationWithIterator, ReplaceHashtableWithMap, ReplaceVectorWithList, ShortInstantiation',
                    'migrating_to_13': 'ReplaceEnumerationWithIterator, ReplaceHashtableWithMap, ReplaceVectorWithList',
                    'migrating_to_14': 'AvoidAssertAsIdentifier',
                    'migrating_to_15': 'AvoidEnumAsIdentifier, ByteInstantiation, IntegerInstantiation, LongInstantiation, ShortInstantiation',
                    'naming': 'AbstractNaming, AvoidDollarSigns, AvoidFieldNameMatchingMethodName, AvoidFieldNameMatchingTypeName, BooleanGetMethodName, ClassNamingConventions, GenericsNaming, LongVariable, MethodNamingConventions, MethodWithSameNameAsEnclosingClass, MisleadingVariableName, MIsLeadingVariableName, NoPackage, PackageCase, ShortClassName, ShortMethodName, ShortVariable, SuspiciousConstantFieldName, SuspiciousEqualsMethodName, SuspiciousHashcodeMethodName, VariableNamingConventions',
                    'optimizations': 'AddEmptyString, AvoidArrayLoops, AvoidInstantiatingObjectsInLoops, LocalVariableCouldBeFinal, MethodArgumentCouldBeFinal, PrematureDeclaration, RedundantFieldInitializer, SimplifyStartsWith, UnnecessaryWrapperObjectCreation, UseArrayListInsteadOfVector, UseArraysAsList, UseStringBufferForStringAppends',
                    'quickstart': 'AbstractClassWithoutAnyMethod, AssignmentInOperand, AssignmentToNonFinalStatic, AvoidAccessibilityAlteration, AvoidBranchingStatementAsLastInLoop, AvoidCatchingThrowable, AvoidDecimalLiteralsInBigDecimalConstructor, AvoidDollarSigns, AvoidInstanceofChecksInCatchClause, AvoidMultipleUnaryOperators, AvoidProtectedFieldInFinalClass, AvoidProtectedMethodInFinalClassNotExtending, AvoidStringBufferField, AvoidThreadGroup, AvoidUsingHardCodedIP, AvoidUsingOctalValues, AvoidUsingVolatile, BadComparison, BigIntegerInstantiation, BooleanInstantiation, BrokenNullCheck, CheckResultSet, CheckSkipResult, ClassCastExceptionWithToArray, ClassNamingConventions, ClassWithOnlyPrivateConstructorsShouldBeFinal, CloneMethodMustBePublic, CloneMethodMustImplementCloneable, CloneMethodReturnTypeMustMatchClassName, CloneThrowsCloneNotSupportedException, CloseResource, CompareObjectsWithEquals, ConstantsInInterface, ControlStatementBraces, DefaultLabelNotLastInSwitchStmt, DoNotCallGarbageCollectionExplicitly, DoNotExtendJavaLangError, DoNotExtendJavaLangThrowable, DontCallThreadRun, DontImportJavaLang, DontUseFloatTypeForLoopIndices, DoubleCheckedLocking, DuplicateImports, EmptyCatchBlock, EmptyFinalizer, EmptyFinallyBlock, EmptyIfStmt, EmptyInitializer, EmptyStatementBlock, EmptyStatementNotInLoop, EmptySwitchStatements, EmptySynchronizedBlock, EmptyTryBlock, EmptyWhileStmt, EqualsNull, ExtendsObject, FinalFieldCouldBeStatic, ForLoopCanBeForeach, ForLoopShouldBeWhileLoop, FormalParameterNamingConventions, GenericsNaming, GuardLogStatement, IdempotentOperations, IdenticalCatchBranches, ImportFromSamePackage, InstantiationToGetClass, JumbledIncrementer, LocalVariableNamingConventions, LogicInversion, LooseCoupling, MethodNamingConventions, MisplacedNullCheck, MissingBreakInSwitch, MissingOverride, MissingStaticMethodInNonInstantiatableClass, NonCaseLabelInSwitchStatement, NonStaticInitializer, NonThreadSafeSingleton, NoPackage, OneDeclarationPerLine, OptimizableToArrayCall, OverrideBothEqualsAndHashcode, PackageCase, PositionLiteralsFirstInCaseInsensitiveComparisons, PositionLiteralsFirstInComparisons, PreserveStackTrace, ProperCloneImplementation, ProperLogger, ReturnEmptyArrayRatherThanNull, ReturnFromFinallyBlock, SimplifiedTernary, SimplifyBooleanReturns, SimplifyConditional, SingleMethodSingleton, SingletonClassReturningNewInstance, SingularField, SuspiciousEqualsMethodName, SuspiciousHashcodeMethodName, SuspiciousOctalEscape, SwitchStmtsShouldHaveDefault, UncommentedEmptyConstructor, UncommentedEmptyMethodBody, UnconditionalIfStatement, UnnecessaryAnnotationValueElement, UnnecessaryConstructor, UnnecessaryConversionTemporary, UnnecessaryFullyQualifiedName, UnnecessaryLocalBeforeReturn, UnnecessaryModifier, UnnecessaryReturn, UnsynchronizedStaticDateFormatter, UnusedFormalParameter, UnusedImports, UnusedLocalVariable, UnusedNullCheckInEquals, UnusedPrivateField, UnusedPrivateMethod, UseAssertEqualsInsteadOfAssertTrue, UseAssertNullInsteadOfAssertTrue, UseAssertSameInsteadOfAssertTrue, UseAssertTrueInsteadOfAssertEquals, UseCollectionIsEmpty, UseEqualsToCompareStrings, UselessOperationOnImmutable, UselessOverridingMethod, UselessParentheses, UselessQualifiedThis, UseLocaleWithCaseConversions, UseNotifyAllInsteadOfNotify, UseUtilityClass',
                    'sunsecure': 'ArrayIsStoredDirectly, MethodReturnsInternalArray',
                    'strictexception': 'AvoidCatchingGenericException, AvoidCatchingNPE, AvoidCatchingThrowable, AvoidLosingExceptionInformation, AvoidRethrowingException, AvoidThrowingNewInstanceOfSameException, AvoidThrowingNullPointerException, AvoidThrowingRawExceptionTypes, DoNotExtendJavaLangError, DoNotThrowExceptionInFinally, ExceptionAsFlowControl, SignatureDeclareThrowsException',
                    'strings': 'AppendCharacterWithChar, AvoidDuplicateLiterals, AvoidStringBufferField, ConsecutiveAppendsShouldReuse, ConsecutiveLiteralAppends, InefficientEmptyStringCheck, InefficientStringBuffering, InsufficientStringBufferDeclaration, StringBufferInstantiationWithChar, StringInstantiation, StringToString, UnnecessaryCaseChange, UseEqualsToCompareStrings, UseIndexOfChar, UselessStringValueOf, UseStringBufferLength',
                    'typeresolution': 'CloneMethodMustImplementCloneable, LooseCoupling, SignatureDeclareThrowsException, UnusedImports',
                    'unnecessary': 'UnnecessaryConversionTemporary, UnnecessaryFinalModifier, UnnecessaryModifier, UnnecessaryReturn, UnusedNullCheckInEquals, UselessOperationOnImmutable, UselessOverridingMethod, UselessParentheses, UselessQualifiedThis',
                    'unusedcode': 'UnusedFormalParameter, UnusedLocalVariable, UnusedPrivateField, UnusedPrivateMethod',

                    # these are new rulesets (as of pmd 6) tha re-organize some rules
                    'bestpractices': 'AbstractClassWithoutAbstractMethod,AccessorClassGeneration,AccessorMethodGeneration,ArrayIsStoredDirectly,AvoidPrintStackTrace,AvoidReassigningLoopVariables,AvoidReassigningParameters,AvoidStringBufferField,AvoidUsingHardCodedIP,CheckResultSet,ConstantsInInterface,DefaultLabelNotLastInSwitchStmt,ForLoopCanBeForeach,ForLoopVariableCount,GuardLogStatement,JUnit4SuitesShouldUseSuiteAnnotation,JUnit4TestShouldUseAfterAnnotation,JUnit4TestShouldUseBeforeAnnotation,JUnit4TestShouldUseTestAnnotation,JUnitAssertionsShouldIncludeMessage,JUnitTestContainsTooManyAsserts,JUnitTestsShouldIncludeAssert,JUnitUseExpected,LooseCoupling,MethodReturnsInternalArray,MissingOverride,OneDeclarationPerLine,PositionLiteralsFirstInCaseInsensitiveComparisons,PositionLiteralsFirstInComparisons,PreserveStackTrace,ReplaceEnumerationWithIterator,ReplaceHashtableWithMap,ReplaceVectorWithList,SwitchStmtsShouldHaveDefault,SystemPrintln,UnusedFormalParameter,UnusedImports,UnusedLocalVariable,UnusedPrivateField,UnusedPrivateMethod,UseAssertEqualsInsteadOfAssertTrue,UseAssertNullInsteadOfAssertTrue,UseAssertSameInsteadOfAssertTrue,UseAssertTrueInsteadOfAssertEquals,UseCollectionIsEmpty,UseTryWithResources,UseVarargs',
                    'multithreading': 'AvoidSynchronizedAtMethodLevel,AvoidThreadGroup,AvoidUsingVolatile,DoNotUseThreads,DontCallThreadRun,DoubleCheckedLocking,NonThreadSafeSingleton,UnsynchronizedStaticDateFormatter,UnsynchronizedStaticFormatter,UseConcurrentHashMap,UseNotifyAllInsteadOfNotify',
                    'performance': 'AddEmptyString,AppendCharacterWithChar,AvoidArrayLoops,AvoidFileStream,AvoidInstantiatingObjectsInLoops,AvoidUsingShortType,BigIntegerInstantiation,BooleanInstantiation,ByteInstantiation,ConsecutiveAppendsShouldReuse,ConsecutiveLiteralAppends,InefficientEmptyStringCheck,InefficientStringBuffering,InsufficientStringBufferDeclaration,IntegerInstantiation,LongInstantiation,OptimizableToArrayCall,RedundantFieldInitializer,ShortInstantiation,SimplifyStartsWith,StringInstantiation,StringToString,TooFewBranchesForASwitchStatement,UnnecessaryWrapperObjectCreation,UseArrayListInsteadOfVector,UseArraysAsList,UseIndexOfChar,UselessStringValueOf,UseStringBufferForStringAppends,UseStringBufferLength',
                    'security': 'HardCodedCryptoKey,InsecureCryptoIv',
                    'errorprone': 'AssignmentInOperand,AssignmentToNonFinalStatic,AvoidAccessibilityAlteration,AvoidAssertAsIdentifier,AvoidBranchingStatementAsLastInLoop,AvoidCallingFinalize,AvoidCatchingNPE,AvoidCatchingThrowable,AvoidDecimalLiteralsInBigDecimalConstructor,AvoidDuplicateLiterals,AvoidEnumAsIdentifier,AvoidFieldNameMatchingMethodName,AvoidFieldNameMatchingTypeName,AvoidInstanceofChecksInCatchClause,AvoidLiteralsInIfCondition,AvoidLosingExceptionInformation,AvoidMultipleUnaryOperators,AvoidUsingOctalValues,BadComparison,BeanMembersShouldSerialize,BrokenNullCheck,CallSuperFirst,CallSuperLast,CheckSkipResult,ClassCastExceptionWithToArray,CloneMethodMustBePublic,CloneMethodMustImplementCloneable,CloneMethodReturnTypeMustMatchClassName,CloneThrowsCloneNotSupportedException,CloseResource,CompareObjectsWithEquals,ConstructorCallsOverridableMethod,DataflowAnomalyAnalysis,DoNotCallGarbageCollectionExplicitly,DoNotCallSystemExit,DoNotExtendJavaLangThrowable,DoNotHardCodeSDCard,DoNotThrowExceptionInFinally,DontImportSun,DontUseFloatTypeForLoopIndices,EmptyCatchBlock,EmptyFinalizer,EmptyFinallyBlock,EmptyIfStmt,EmptyInitializer,EmptyStatementBlock,EmptyStatementNotInLoop,EmptySwitchStatements,EmptySynchronizedBlock,EmptyTryBlock,EmptyWhileStmt,EqualsNull,FinalizeDoesNotCallSuperFinalize,FinalizeOnlyCallsSuperFinalize,FinalizeOverloaded,FinalizeShouldBeProtected,IdempotentOperations,ImportFromSamePackage,InstantiationToGetClass,InvalidSlf4jMessageFormat,JumbledIncrementer,JUnitSpelling,JUnitStaticSuite,LoggerIsNotStaticFinal,MethodWithSameNameAsEnclosingClass,MisplacedNullCheck,MissingBreakInSwitch,MissingSerialVersionUID,MissingStaticMethodInNonInstantiatableClass,MoreThanOneLogger,NonCaseLabelInSwitchStatement,NonStaticInitializer,NullAssignment,OverrideBothEqualsAndHashcode,ProperCloneImplementation,ProperLogger,ReturnEmptyArrayRatherThanNull,ReturnFromFinallyBlock,SimpleDateFormatNeedsLocale,SingleMethodSingleton,SingletonClassReturningNewInstance,StaticEJBFieldShouldBeFinal,StringBufferInstantiationWithChar,SuspiciousEqualsMethodName,SuspiciousHashcodeMethodName,SuspiciousOctalEscape,TestClassWithoutTestCases,UnconditionalIfStatement,UnnecessaryBooleanAssertion,UnnecessaryCaseChange,UnnecessaryConversionTemporary,UnusedNullCheckInEquals,UseCorrectExceptionLogging,UseEqualsToCompareStrings,UselessOperationOnImmutable,UseLocaleWithCaseConversions,UseProperClassLoader',
                    'documentation': 'CommentContent,CommentRequired,CommentSize,UncommentedEmptyConstructor,UncommentedEmptyMethodBody',
                    'design': 'AbstractClassWithoutAnyMethod,AvoidCatchingGenericException,AvoidDeeplyNestedIfStmts,AvoidRethrowingException,AvoidThrowingNewInstanceOfSameException,AvoidThrowingNullPointerException,AvoidThrowingRawExceptionTypes,ClassWithOnlyPrivateConstructorsShouldBeFinal,CollapsibleIfStatements,CouplingBetweenObjects,CyclomaticComplexity,DataClass,DoNotExtendJavaLangError,ExceptionAsFlowControl,ExcessiveClassLength,ExcessiveImports,ExcessiveMethodLength,ExcessiveParameterList,ExcessivePublicCount,FinalFieldCouldBeStatic,GodClass,ImmutableField,LawOfDemeter,LogicInversion,LoosePackageCoupling,ModifiedCyclomaticComplexity,NcssConstructorCount,NcssCount,NcssMethodCount,NcssTypeCount,NPathComplexity,SignatureDeclareThrowsException,SimplifiedTernary,SimplifyBooleanAssertion,SimplifyBooleanExpressions,SimplifyBooleanReturns,SimplifyConditional,SingularField,StdCyclomaticComplexity,SwitchDensity,TooManyFields,TooManyMethods,UselessOverridingMethod,UseObjectForClearerAPI,UseUtilityClass',
                    'codestyle': 'AbstractNaming,AtLeastOneConstructor,AvoidDollarSigns,AvoidFinalLocalVariable,AvoidPrefixingMethodParameters,AvoidProtectedFieldInFinalClass,AvoidProtectedMethodInFinalClassNotExtending,AvoidUsingNativeCode,BooleanGetMethodName,CallSuperInConstructor,ClassNamingConventions,CommentDefaultAccessModifier,ConfusingTernary,ControlStatementBraces,DefaultPackage,DontImportJavaLang,DuplicateImports,EmptyMethodInAbstractClassShouldBeAbstract,ExtendsObject,FieldDeclarationsShouldBeAtStartOfClass,FieldNamingConventions,ForLoopShouldBeWhileLoop,ForLoopsMustUseBraces,FormalParameterNamingConventions,GenericsNaming,IdenticalCatchBranches,IfElseStmtsMustUseBraces,IfStmtsMustUseBraces,LinguisticNaming,LocalHomeNamingConvention,LocalInterfaceSessionNamingConvention,LocalVariableCouldBeFinal,LocalVariableNamingConventions,LongVariable,MDBAndSessionBeanNamingConvention,MethodArgumentCouldBeFinal,MethodNamingConventions,MIsLeadingVariableName,NoPackage,OnlyOneReturn,PackageCase,PrematureDeclaration,RemoteInterfaceNamingConvention,RemoteSessionInterfaceNamingConvention,ShortClassName,ShortMethodName,ShortVariable,SuspiciousConstantFieldName,TooManyStaticImports,UnnecessaryAnnotationValueElement,UnnecessaryConstructor,UnnecessaryFullyQualifiedName,UnnecessaryLocalBeforeReturn,UnnecessaryModifier,UnnecessaryReturn,UseDiamondOperator,UselessParentheses,UselessQualifiedThis,UseUnderscoresInNumericLiterals,VariableNamingConventions,WhileLoopsMustUseBraces'
                    }
